wheat:
  experience: 1
  harvest_required: 16
beetroot:
  experience: 1
  harvest_required: 16
potato:
  experience: 1
  harvest_required: 16
carrot:
  experience: 1
  harvest_required: 16
pumpkin:
  experience: 1
  harvest_required: 8
melon:
  experience: 1
  harvest_required: 8
sugar_cane:
  experience: 1
  harvest_required: 16
wood_hoe:
  reduction: 0
stone_hoe:
  reduction: 0
gold_hoe:
  reduction: 1
iron_hoe:
  reduction: 2
diamond_hoe:
  reduction: 3
hoe_type_reducing_harvest: true
hoe_tool_required: true
