wheat: {
  experience: 1,
  harvest_required: 10
}
beetroot: {
  experience: 1,
  harvest_required: 10
}
potato: {
  experience: 1,
  harvest_required: 10
}
carrot: {
  experience: 1,
  harvest_required: 10
}
pumpkin: {
  experience: 1,
  harvest_required: 10
}
melon: {
  experience: 1,
  harvest_required: 10
}
hoe_tool_required: false


