main: "com.jsonmack.mcplugins.silktouch_spawner.SilkTouchSpawnerPlugin"
name: "SilkTouchSpawner"
description: "Allows the player to receive the respective spawner when breaking with a diamond axe with Silk Touch enchantment."
version: "1.0.0"
api-version: "1.15"
author: "BitLong"

commands:
  spawner:
    usage: "/<spawner> <type>"
    permission: "op"
    description: "Create a spawner of a certain type at this location."
