name: 'WolrdTeleport'
version: '1.9'
api-version: '1.15'
main: 'com.jsonmack.worldteleport.TeleportModulePlugin'
description: 'A plugin that allows you to create structures that can teleport you around the world'
commands:
  teleportmodule:
    description: 'Change the default configuration values for the world teleport module.'
    permission: 'op'
